bannerTitle : 'OUR SERVICES'
bannerDescription : 'We don’t like to be everything to everyone. We would rather be something to someone, you. Bespoke design services from the house of Little Brahma. Each of our cosmic diagrams (Mandala) promises instinctive work and transformational execution. 
"We meditate on these all-day long"'
